WIP: Refactor view pages using react (tables)
dbmdz/cudami pull request #1003
Opened 2021-05-06 16:31 UTC by daforster

Ticket: [mdz/webapps/internal/cudami/webapp#46]

This PR replaces some more tables by react on the `view` pages.

2021-05-18 09:54 UTC, morpheus-87 requested changes

2021-05-18 09:54 UTC, morpheus-87 commented on dc-cudami-admin/src/main/resources/templates/digitalobjects/view.html
> +        enableSearch: false,
Das kannst du dir sparen, ist per Default `false`.

2021-05-18 09:54 UTC, morpheus-87 commented on dc-cudami-admin/src/main/resources/templates/digitalobjects/view.html
> +        enableSearch: false,
Das kannst du dir sparen, ist per Default `false`.

2021-05-18 09:54 UTC, morpheus-87 commented on dc-cudami-admin/src/main/resources/templates/topics/view.html
> +        enableRemove: false,
Die Zeilen 122 - 124 kannst du dir sparen, ist per Default `false`.

2021-05-18 09:54 UTC, morpheus-87 commented on dc-cudami-admin/src/main/resources/templates/topics/view.html
> +        showNew: false,
Die Zeilen 129 - 130 kannst du dir sparen, ist per Default `false`.

2021-05-18 09:54 UTC, morpheus-87 commented on dc-cudami-admin/src/main/resources/templates/topics/view.html
> +        enableRemove: true,
Die Zeilen 137 - 139 bitte entfernen, die Funktionalität ist doch nicht implementiert, oder?

2021-05-18 09:54 UTC, morpheus-87 commented on dc-cudami-admin/src/main/resources/templates/topics/view.html
> +        showNew: false,
Die Zeilen 144 - 145 kannst du dir sparen, ist per Default `false`.

2021-05-18 09:54 UTC, morpheus-87 commented on dc-cudami-editor/src/locales/de/translation.json
> +    "entity_plural": "Objekte",
Das fehlt noch unter `totalElements`.

2021-05-18 09:54 UTC, morpheus-87 commented on dc-cudami-editor/src/locales/en/translation.json
> +    "entity_plural": "Entities",
Das fehlt noch unter `totalElements`.

2021-05-18 16:04 UTC, daforster commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/entity/TopicRepositoryImpl.java
> +  }
Damit müssten wir eine saubere Lösung (kein doppelter Code) haben, bis wir den `PageRequest` mit einer "allItems"-Property ausgestattet haben ;-)

2021-05-19 06:02 UTC, morpheus-87 requested changes

2021-05-20 11:23 UTC, morpheus-87 approved these changes

2021-05-20 11:32 UTC, merged