Draft: V5 compatibility
dbmdz/cudami pull request #1043
Opened 2021-05-31 12:23 UTC by clorenz

- Umstellung aller Controller und Clients auf `v5`-URLs
- Ein Teil der Controller wurde versioniert, um Kompatibilität mit Alt-Clients (altes Model) sicherzustellen

2021-05-31 14:14 UTC, morpheus-87 requested changes

2021-05-31 14:14 UTC, morpheus-87 commented on dc-cudami-client/src/main/java/de/digitalcollections/cudami/client/identifiable/agent/CudamiFamilyNamesClient.java
> +        doGetRequestForPagedObjectList("/v5/familynames", searchPageRequest);
Wenn man hier `doGetSearchRequestForPagedObjectList` verwendet, kann man sich wohl den Cast auf `SearchPageResponse` sparen.

2021-05-31 14:45 UTC, clorenz commented on dc-cudami-client/src/main/java/de/digitalcollections/cudami/client/identifiable/agent/CudamiFamilyNamesClient.java
> +        doGetRequestForPagedObjectList("/v5/familynames", searchPageRequest);
Leider nicht, die `doGetRequestForPagedObjectList` gibt nur eine `PageResponse` zurück, und das wird dann bemängelt

2021-06-01 05:12 UTC, morpheus-87 commented on dc-cudami-client/src/main/java/de/digitalcollections/cudami/client/identifiable/agent/CudamiFamilyNamesClient.java
> +        doGetRequestForPagedObjectList("/v5/familynames", searchPageRequest);
Deswegen meine ich ja auch, dass du `doGetSearchRequestForPagedObjectList` verwenden könntest.

2021-06-02 08:03 UTC, clorenz commented on dc-cudami-client/src/main/java/de/digitalcollections/cudami/client/identifiable/agent/CudamiFamilyNamesClient.java
> +        doGetRequestForPagedObjectList("/v5/familynames", searchPageRequest);
Fix ist eingechecked.

2021-06-02 08:20 UTC, morpheus-87 commented on dc-cudami-client/src/main/java/de/digitalcollections/cudami/client/identifiable/agent/CudamiFamilyNamesClient.java
> +        doGetRequestForPagedObjectList("/v5/familynames", searchPageRequest);
:+1:

2021-06-07 12:22 UTC, morpheus-87 approved these changes

2021-06-07 12:29 UTC, merged