Draft: Controller and service layer for short links
dbmdz/cudami pull request #1167
Opened 2021-08-23 10:22 UTC by clorenz

2021-09-14 13:10 UTC, morpheus-87 requested changes

2021-09-14 13:10 UTC, morpheus-87 commented on dc-cudami-server/dc-cudami-server-webapp/src/main/java/de/digitalcollections/cudami/server/controller/ControllerException.java
> +}
Sollte die Klasse nicht `CudamiControllerException` heißen?

2021-09-14 13:10 UTC, morpheus-87 commented on dc-cudami-server/dc-cudami-server-webapp/src/main/resources/application.yml
> +    generationExcludes: [DIGITAL_OBJECT]
Ich würde hier erstmal die leere Liste angeben, für unsere Zwecke können wir das von außen dann entsprechend überschreiben.

2021-09-14 13:10 UTC, morpheus-87 commented on dc-cudami-server/dc-cudami-server-webapp/src/test/java/de/digitalcollections/cudami/server/controller/identifiable/alias/UrlAliasControllerTest.java
> +            + "}";
Kann man das nicht in eine Datei auslagern?

2021-09-14 13:10 UTC, morpheus-87 commented on dc-cudami-server/dc-cudami-server-webapp/src/test/java/de/digitalcollections/cudami/server/controller/identifiable/alias/UrlAliasControllerTest.java
> +            + "}";
Kann man das nicht in eine Datei auslagern?

2021-09-14 13:10 UTC, morpheus-87 commented on dc-cudami-server/dc-cudami-server-webapp/src/test/java/de/digitalcollections/cudami/server/controller/identifiable/alias/UrlAliasControllerTest.java
> +            + "}";
Kann man das nicht in eine Datei auslagern?

2021-09-14 14:08 UTC, clorenz commented on contributing.md
> +createdb -U cudami cudami
sind ausgebaut

2021-09-14 14:08 UTC, clorenz commented on dc-cudami-client/pom.xml
> +    </dependency>
nein, noch nicht, daher ist sie jetzt wieder ausgebaut.

2021-09-14 14:09 UTC, clorenz commented on dc-cudami-server/dc-cudami-server-webapp/src/main/java/de/digitalcollections/cudami/server/controller/ControllerException.java
> +}
Stimmt... Ist umbenannt und an den entsprechenden Stellen, die sie verwenden, angepaßt

2021-09-15 07:07 UTC, clorenz commented on dc-cudami-admin/src/main/resources/templates/webpages/view.html
> +                  </th:block>
ja :-)

2021-09-15 07:12 UTC, morpheus-87 commented on dc-cudami-admin/src/main/resources/templates/webpages/view.html
> +                  </th:block>
:+1:

2021-09-16 14:11 UTC, clorenz commented on dc-cudami-server/dc-cudami-server-webapp/src/main/resources/application.yml
> +    generationExcludes: [DIGITAL_OBJECT]
erledigt

2021-09-21 07:55 UTC, daforster approved these changes

2021-09-21 07:55 UTC, merged