Draft: Fixed sql injection for filtering values. compiles and unit tests val…
dbmdz/cudami pull request #1198
Opened 2021-09-10 13:46 UTC by datazuul

…id. massive testing needed (TODO/FIXME)

2021-09-15 09:52 UTC, daforster requested changes

2021-09-15 09:52 UTC, daforster commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/test/java/de/digitalcollections/cudami/server/backend/impl/jdbi/JdbiRepositoryImplTest.java
> +  public void testGetFilterClauses() {}
Fehlt hier nicht etwas? :wink:

2021-09-16 06:23 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/test/java/de/digitalcollections/cudami/server/backend/impl/jdbi/JdbiRepositoryImplTest.java
> +  public void testGetFilterClauses() {}
ooops. removed

2021-09-16 07:59 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/JdbiRepositoryImpl.java
> +      final String leftSide = (columnName != null) ? columnName : fieldName;
only if column name != null otherwise illegalargumentexception

2021-09-16 08:39 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/JdbiRepositoryImpl.java
> +          for (Object value : fc.getValues()) {
normale for schleife

2021-09-16 08:39 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/JdbiRepositoryImpl.java
> +    for (FilterCriterion filterCriterion : filterCriteria) {
normale for schleife

2021-09-16 08:39 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/entity/CollectionRepositoryImpl.java
> +        Filtering.defaultBuilder().filter("cc.child_collection_uuid").isEquals(uuid).build();
add internal filter builder with safe not to be resolved column  names. not to be used in controllers / for user input / urls

2021-09-16 08:39 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/entity/CollectionRepositoryImpl.java
> +    argumentMappings.put("searchTerm", this.escapeTermForJsonpath(searchTerm));
remove this.

2021-09-16 08:39 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/entity/EntityRepositoryImpl.java
> +    Filtering filtering = Filtering.defaultBuilder().filter("refid").isEquals(refId).build();
```suggestion
    Filtering filtering = Filtering.defaultBuilder().filter("refId").isEquals(refId).build();
```

2021-09-16 08:39 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/test/java/de/digitalcollections/cudami/server/backend/impl/jdbi/JdbiRepositoryImplTest.java
> +    String whereClause = instance.getWhereClause(fc, argumentMappings, 17);
42

2021-09-16 08:39 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-webapp/src/main/java/de/digitalcollections/cudami/server/controller/converter/StringToFilterCriteriaGenericConverter.java
> +    } else if (filterOperation.getOperandCount() == FilterOperation.OperandCount.SINGLEVALUE) {
remove else

2021-09-16 08:39 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-webapp/src/main/java/de/digitalcollections/cudami/server/controller/converter/StringToFilterCriteriaGenericConverter.java
> +    return null;
throw illegalargumentexception / unsupportedoperation

2021-09-16 11:26 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/JdbiRepositoryImpl.java
> +          for (Object value : fc.getValues()) {
ehrlich gesagt, finde ich den code nicht besser:

```
Object[] valuesArray = fc.getValues().toArray();
          for (int valueCount = 1; valueCount < valuesArray.length; valueCount++) {
            Object value = valuesArray[valueCount - 1];
            String key = criterionKey + "_" + valueCount;
            values.add(":" + key);
            argumentMappings.put(key, value);
          }
```

vorher (besser meiner meinung nach):

```
int valueCount = 1;
          for (Object value : fc.getValues()) {
            String key = criterionKey + "_" + valueCount;
            values.add(":" + key);
            argumentMappings.put(key, value);
            valueCount++;
          }
```

2021-09-17 06:46 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/JdbiRepositoryImpl.java
> +          for (Object value : fc.getValues()) {
replaced by stream

2021-09-17 07:00 UTC, jbaiter commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/JdbiRepositoryImpl.java
> +      if (leftSide.contains("'") || leftSide.contains(";")) {
Glaube das beste wäre hier einfach ne wirklich strenge Regular Expression, links darf ja wirklihc nur ein Feldname stehen, d.h. da kann man wahrscheinlich wirklich auf `[a-ZA-Z0-9]{1,32}` oder so gehen.

2021-09-17 07:05 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-webapp/src/main/java/de/digitalcollections/cudami/server/controller/converter/StringToFilterCriteriaGenericConverter.java
> +    } else if (filterOperation.getOperandCount() == FilterOperation.OperandCount.SINGLEVALUE) {
done

2021-09-17 07:05 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-webapp/src/main/java/de/digitalcollections/cudami/server/controller/converter/StringToFilterCriteriaGenericConverter.java
> +    return null;
done

2021-09-17 09:48 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/JdbiRepositoryImpl.java
> +      final String leftSide = (columnName != null) ? columnName : fieldName;
fixed

2021-09-17 09:48 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/entity/CollectionRepositoryImpl.java
> +        Filtering.defaultBuilder().filter("cc.child_collection_uuid").isEquals(uuid).build();
added "filterNative" to builder

2021-09-17 09:48 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/test/java/de/digitalcollections/cudami/server/backend/impl/jdbi/JdbiRepositoryImplTest.java
> +    String whereClause = instance.getWhereClause(fc, argumentMappings, 17);
done

2021-09-17 09:59 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/JdbiRepositoryImpl.java
> +      if (leftSide.contains("'") || leftSide.contains(";")) {
gelöst: string der linken seite wird bei user eingabe (URL) immer auf einen column namen gematcht (mit string vergleich). wenn kein match (sql-injection) gibt es eine IllegalArgumentException

2021-09-17 10:08 UTC, jbaiter commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/JdbiRepositoryImpl.java
> +      if (leftSide.contains("'") || leftSide.contains(";")) {
Das macht der Code momentan aber nicht, der wirft ne IAE nur wenn der Feldname Semikolon oder Space enthält, nicht wenn der Feldname nicht auf nen Column-Namen gemappt werden kann.

Wenn das schon ne Ebene oben drüber gemacht wird, dann kann man sich die ganze Passage hier sparen, oder?

2021-09-17 10:16 UTC, jbaiter approved these changes
Soweit ich das beurteilen kann ist damit die Lücke geschlossen, hab jetzt aber aufgrund der Masse an Änderungen nicht komplett durchsteigen können was genau passiert sondern nur an den neuralgischen Stellen geguckt.

2021-09-17 10:35 UTC, daforster approved these changes

2021-09-17 11:06 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/JdbiRepositoryImpl.java
> +      if (leftSide.contains("'") || leftSide.contains(";")) {
der code hat sich inzwischen geändert. diese ansicht in gitlab hat sich nicht aktualisiert?

2021-09-17 12:15 UTC, merged