Fix UrlAlias generation for sub-pages
dbmdz/cudami pull request #1283
Opened 2021-11-03 11:42 UTC by clorenz

Fix UrlAlias generation for sub-pages

To make this Fix effective, you have to re-run the migration (and hope, that nobody entered or modified UrlAliases yet), by
deleting the old one in the database:

```
delete from url_aliases;
delete from flyway_schema_history where version='9.02.02';
```

2021-11-03 16:06 UTC, daforster requested changes

2021-11-03 16:06 UTC, daforster commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/database/migration/V9_02_02__DML_Fill_urlaliases.java
> +            + "' and ww.child_webpage_uuid=w.uuid";
Dieser Select ist sehr implizit (geht natürlich) und ich hab wirklich eine Weile gebraucht, den zu verstehen. Ich würde hier etwas deutlicher mit `INNER JOIN ... ON ...` arbeiten. Das würde den Select auch noch beschleunigen.

2021-11-03 16:06 UTC, daforster commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/database/migration/V9_02_02__DML_Fill_urlaliases.java
> +          "{}: Building slug with suffix={}", entityType != null ? entityType : "WEBPAGE", slug);
:+1:

2021-11-04 08:07 UTC, clorenz commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/database/migration/V9_02_02__DML_Fill_urlaliases.java
> +            + parentWebpageUuid
Wäre auch meine Präferenz gewesen, aber JDBCTemplate unterstützt das nicht direkt, und indirekt hätte ich die halbe Migration umbauen müssen.
Da die Migration aber nur 1x laufen wird, und eine SQLInjection hier ausgeschlossen ist, habe ich den pragmatischen Weg gewählt.

2021-11-04 09:42 UTC, clorenz commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/database/migration/V9_02_02__DML_Fill_urlaliases.java
> +      throw new RuntimeException("Cannot parse " + w + ": " + e, e);
Ja. Ist korrigiert (und auch an den anderen betroffenen Stellen)

2021-11-04 09:42 UTC, clorenz commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/database/migration/V9_02_02__DML_Fill_urlaliases.java
> +      Map<String, String> w,
Ja. Sind jetzt draußen

2021-11-04 09:42 UTC, clorenz commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/database/migration/V9_02_02__DML_Fill_urlaliases.java
> +            + "' and ww.child_webpage_uuid=w.uuid";
wie besprochen

2021-11-04 16:08 UTC, daforster commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/database/migration/V9_02_02__DML_Fill_urlaliases.java
> +            + "' and ww.child_webpage_uuid=w.uuid";
```suggestion
        "SELECT w.uuid AS w_uuid, w.label AS label FROM webpages w INNER JOIN webpage_webpages ww ON ww.child_webpage_uuid=w.uuid WHERE ww.parent_webpage_uuid = '"
            + parentWebpageUuid + "'";
```
Sowas schwebt mir da vor :thinking:

2021-11-04 16:24 UTC, clorenz commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/database/migration/V9_02_02__DML_Fill_urlaliases.java
> +            + "' and ww.child_webpage_uuid=w.uuid";
getestet und für gut befunden ;-)

2021-11-04 16:36 UTC, daforster approved these changes

2021-11-04 16:44 UTC, merged