Draft: Make (parts of) configuration available via an endpoint
dbmdz/cudami pull request #1362
Opened 2021-12-09 15:57 UTC by clorenz

Make configuration parameters, such as UrlAlias params (excluded identifiables, max length) and defaults (language, locale) available via an own endpoint.

2021-12-16 13:21 UTC, morpheus-87 requested changes

2021-12-16 13:21 UTC, morpheus-87 commented on dc-cudami-server/dc-cudami-server-backend-inmemory/src/main/java/de/digitalcollections/cudami/server/backend/inmemory/LocaleRepositoryImpl.java
> +  @Autowired
Das sollte man sich sparen können.

2021-12-16 14:02 UTC, daforster commented on dc-cudami-server/dc-cudami-server-webapp/src/main/java/de/digitalcollections/cudami/server/config/CudamiServerConfig.java
> +public class CudamiServerConfig extends CudamiConfig {}
`/dc-cudami-server-business/src/main/java/de/digitalcollections/cudami/server/config/UrlAliasGenerationProperties.java` sollte damit überflüssig werden. Könntest Du das bei der Gelegenheit gleich noch refactoren? Ich glaube, das wird nur im `IdentifiableServiceImpl` genutzt.

2021-12-16 15:43 UTC, clorenz commented on dc-cudami-server/dc-cudami-server-backend-inmemory/src/main/java/de/digitalcollections/cudami/server/backend/inmemory/LocaleRepositoryImpl.java
> +  @Autowired
ist draußen

2021-12-16 15:45 UTC, clorenz commented on dc-cudami-model/src/main/java/de/digitalcollections/cudami/model/config/CudamiConfig.java
> +  public static class UrlAlias {
wie besprochen, das korrelliert mit der entsprechenden Property. Da wir entweder die Property umbenennen, oder aber Annotations ins Model neu einbringen müßten, belassen wir es erstmal dabei.

2021-12-16 15:45 UTC, clorenz commented on dc-cudami-server/dc-cudami-server-webapp/src/main/java/de/digitalcollections/cudami/server/config/CudamiServerConfig.java
> +public class CudamiServerConfig extends CudamiConfig {}
Ist gefixed, wobei der IdentifiableService die untereste Ebene war, was einige Refactorings zur Folge hatte.

2021-12-16 16:02 UTC, daforster approved these changes

2021-12-16 16:03 UTC, daforster commented on dc-cudami-server/dc-cudami-server-webapp/src/main/java/de/digitalcollections/cudami/server/config/CudamiServerConfig.java
> +public class CudamiServerConfig extends CudamiConfig {}
Jaa, das ist immer ein riesen Spaß :roll_eyes:

2021-12-20 10:53 UTC, morpheus-87 approved these changes

2021-12-20 11:06 UTC, merged