Duplicate information
dbmdz/cudami pull request #1374
Opened 2021-12-14 12:17 UTC by morpheus-87

This PR adds a feedback message about duplicate slugs.

2021-12-14 12:25 UTC, clorenz requested changes

2021-12-14 12:25 UTC, clorenz commented on dc-cudami-editor/src/locales/de/translation.json
> +      "urlAliases_other": "Die angezeigten sprechenden Links wurden ggf. um ein numerisches Suffix ergänzt. Bitte prüfen Sie, ob Duplikate vorliegt."
```suggestion
      "urlAliases_other": "Die angezeigten sprechenden Links wurden ggf. um ein numerisches Suffix ergänzt. Bitte prüfen Sie, ob Duplikate vorliegen."
```

2021-12-14 12:31 UTC, morpheus-87 commented on dc-cudami-editor/src/locales/de/translation.json
> +      "urlAliases_other": "Die angezeigten sprechenden Links wurden ggf. um ein numerisches Suffix ergänzt. Bitte prüfen Sie, ob Duplikate vorliegt."
Ist korrigiert, vielen Dank!

2021-12-14 15:23 UTC, daforster approved these changes

2021-12-14 15:23 UTC, daforster commented on dc-cudami-editor/src/locales/de/translation.json
> +      "urlAliases_other": "Die angezeigten sprechenden Links wurden ggf. um ein numerisches Suffix ergänzt. Bitte prüfen Sie, ob Duplikate vorliegen."
Schön offen formuliert! Gefällt mir gut :+1:

2021-12-15 07:54 UTC, clorenz approved these changes

2021-12-15 07:59 UTC, merged