Add unique field getter to make unique sorting possible
dbmdz/cudami pull request #1472
Opened 2022-02-03 16:50 UTC by daforster

Should be merged **after** release of 5.2.0

2022-02-07 14:32 UTC, morpheus-87 requested changes

2022-02-07 14:32 UTC, morpheus-87 commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/alias/UrlAliasRepositoryImpl.java
> +        List.of("created", "lastPublished", "\"primary\"", "slug", "targetLanguage"));
Könnte man hier nicht auch `Arrays.asList` verwenden?

2022-02-07 14:32 UTC, morpheus-87 commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/relation/PredicateRepositoryImpl.java
> +    return "value";
Wäre hier nicht `null` sinnvoller? `value` ist ja oben schon drin.

2022-02-08 09:46 UTC, daforster commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/relation/PredicateRepositoryImpl.java
> +    return "value";
`value` oben raus

2022-02-08 09:46 UTC, daforster commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/alias/UrlAliasRepositoryImpl.java
> +        List.of("created", "lastPublished", "\"primary\"", "slug", "targetLanguage"));
:heavy_check_mark:

2022-02-08 10:04 UTC, morpheus-87 approved these changes

2022-02-08 10:09 UTC, merged