Optimize label sorting
dbmdz/cudami pull request #1524
Opened 2022-03-04 11:26 UTC by daforster

...by using `COALESCE` to implement the fallback and using unicode collation to speed up sorting.

2022-03-04 13:29 UTC, daforster commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/database/AbstractPagingAndSortingRepositoryImpl.java
> +        }
`else`: `,` einfügen

2022-03-04 15:24 UTC, daforster commented
Kann eigentlich gemergt werden, wenn approved :slightly_smiling_face:

2022-03-14 06:35 UTC, morpheus-87 commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/IdentifiableRepositoryImpl.java
> +        "(?i)(([\\w._]+)->>'.+?') +(asc|desc)", "COALESCE($1, $2->>'') COLLATE \"ucs_basic\" $3");
Könntest du hier eventuell die Gruppen noch benennen? Scheint jedenfalls zu gehen: https://stackoverflow.com/questions/30902305/java-string-replaceall-backreference-with-named-groups

2022-03-14 06:36 UTC, morpheus-87 requested changes

2022-03-14 06:36 UTC, morpheus-87 commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/IdentifiableRepositoryImpl.java
> +        "(?i)(([\\w._]+)->>'.+?') +(asc|desc)", "COALESCE($1, $2->>'') COLLATE \"ucs_basic\" $3");
Könntest du hier eventuell die Gruppen noch benennen? Scheint jedenfalls zu gehen: https://stackoverflow.com/questions/30902305/java-string-replaceall-backreference-with-named-groups

2022-03-14 06:36 UTC, morpheus-87 commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/database/AbstractPagingAndSortingRepositoryImpl.java
> +          sqlQuery.append(",");
```suggestion
          sqlQuery.append(", ");
```

2022-03-14 12:08 UTC, daforster commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/IdentifiableRepositoryImpl.java
> +        "(?i)(([\\w._]+)->>'.+?') +(asc|desc)", "COALESCE($1, $2->>'') COLLATE \"ucs_basic\" $3");
:+1:

2022-03-14 12:34 UTC, morpheus-87 approved these changes

2022-03-14 13:31 UTC, merged