Objecttype
dbmdz/cudami pull request #1711
Opened 2022-05-24 13:32 UTC by datazuul

Replacing EntityType with IdentifiableObjectType (in all entities and urlaliases)

TODO: 1 failing spotbugs (possible NPE) to be fixed

2022-05-24 13:35 UTC, clorenz submitted a review, later dismissed

2022-05-24 13:50 UTC, daforster commented
Wird dadurch nicht der `EntityType` obsolet? Mir scheint bei Entities der `EntityType` immer gleich dem `IdentifiableObjectType` zu sein. Braucht's das wirklich doppelt?

2022-05-30 07:21 UTC, morpheus-87 requested changes

2022-05-30 07:21 UTC, morpheus-87 commented on CHANGELOG.md
> +- Added Handling of `identifiableObjectType` for `Identifiable`s
```suggestion
- Added handling of `identifiableObjectType` for `Identifiable`s
```

2022-05-30 08:32 UTC, morpheus-87 approved these changes

2022-05-30 08:32 UTC, clorenz approved these changes
lokaler Test war erfolgreich

2022-05-30 08:34 UTC, merged