Find items by part_of_item uuid
dbmdz/cudami pull request #1820
Opened 2022-06-24 14:14 UTC by clorenz

2022-06-24 15:20 UTC, daforster requested changes

2022-06-24 15:20 UTC, daforster commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/entity/work/ItemRepositoryImpl.java
> +    }
```suggestion
```

2022-06-24 15:20 UTC, daforster commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/entity/work/ItemRepositoryImpl.java
> +        return null;
```suggestion
        return super.getColumnName(modelProperty);
```

2022-06-27 09:47 UTC, clorenz commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/entity/work/ItemRepositoryImpl.java
> +    }
done

2022-06-27 09:47 UTC, clorenz commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/entity/work/ItemRepositoryImpl.java
> +        return null;
done

2022-06-29 14:06 UTC, daforster approved these changes

2022-06-29 14:54 UTC, merged