First working buckets endpoint
dbmdz/cudami pull request #1889
Opened 2022-07-18 15:20 UTC by datazuul

2022-08-04 12:03 UTC, morpheus-87 requested changes

2022-08-04 12:03 UTC, morpheus-87 commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/semantic/HeadwordRepositoryImpl.java
> +            + " hws AS (SELECT * FROM headwords_list WHERE num between (select num from headwords_list where uuid = :startUuid) AND (select num from headwords_list where uuid = :endUuid))";
```suggestion
            + " hws AS (SELECT * FROM headwords_list WHERE num BETWEEN (SELECT num FROM headwords_list WHERE uuid = :startUuid) AND (SELECT num FROM headwords_list WHERE uuid = :endUuid))";
```

2022-08-04 12:37 UTC, daforster commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/semantic/HeadwordRepositoryImpl.java
> +        " buckets AS (SELECT num, uuid, label, ntile(:numberOfBuckets) OVER (ORDER BY label ASC) FROM hws),"
Nein, das ist eine Funktion, die eigentlich klein geschrieben wird.

2022-08-04 13:27 UTC, morpheus-87 requested changes

2022-08-04 13:27 UTC, morpheus-87 commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/semantic/HeadwordRepositoryImpl.java
> +            + " headwords_list AS (SELECT ROW_NUMBER() OVER (ORDER BY label) as num, uuid, label FROM "
```suggestion
            + " headwords_list AS (SELECT row_number() OVER (ORDER BY label) as num, uuid, label FROM "
```

2022-08-04 14:00 UTC, daforster requested changes

2022-08-04 15:03 UTC, daforster commented
Die Collation steht (auf DEV) für `label` und `locale` schon auf `ucs_basic`, also Unicode. Da `(label, locale)` unique sind, ist auch ein passender Index bereits vorhanden. Man müsste noch schauen, ob dieser auch bei `order by label` (also ohne `locale`) benutzt wird; wenn nicht, sollte noch ein Index aufs Label angelegt werden.

2022-08-05 13:43 UTC, datazuul commented on dc-cudami-client/src/main/java/de/digitalcollections/client/BaseRestClient.java
> -  private HttpRequest createDeleteRequest(String requestUrl) {
wieder protected, done

2022-08-05 13:44 UTC, datazuul commented on dc-cudami-client/src/main/java/de/digitalcollections/cudami/client/semantic/CudamiHeadwordsClient.java
> +    }
done, methoden aus BaseRestClient werden nun verwendet

2022-08-08 08:21 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/semantic/HeadwordRepositoryImpl.java
> +              + " hws AS (SELECT * FROM headwords_list WHERE num between (select num from headwords_list where uuid = :startUuid) AND (select num from headwords_list where uuid = :endUuid)),");
durch range ersetzt

2022-08-08 08:22 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/semantic/HeadwordRepositoryImpl.java
> +            + " buckets_borders_nums AS (SELECT min(num) AS minNum, max(num) AS maxNum, ntile FROM buckets GROUP BY ntile ORDER BY ntile)"
done

2022-08-08 08:22 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/semantic/HeadwordRepositoryImpl.java
> +            + " SELECT num, uuid, label, ntile FROM buckets"
done

2022-08-08 08:22 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/semantic/HeadwordRepositoryImpl.java
> +            + " WHERE num IN ((SELECT minNum FROM buckets_borders_nums) UNION (SELECT maxNum FROM buckets_borders_nums))");
done

2022-08-08 08:22 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/semantic/HeadwordRepositoryImpl.java
> +            + " hws AS (SELECT * FROM headwords_list WHERE num between (select num from headwords_list where uuid = :startUuid) AND (select num from headwords_list where uuid = :endUuid))";
done

2022-08-08 08:31 UTC, datazuul commented
> 
it si ok, no further index needed:

https://use-the-index-luke.com/sql/where-clause/the-equals-operator/concatenated-keys

In general, a database can use a concatenated index when searching with the leading (leftmost) columns. An index with three columns can be used when searching for the first column, when searching with the first two columns together, and when searching using all columns.

Even though the two-index solution delivers very good select performance as well, the single-index solution is preferable. It not only saves storage space, but also the maintenance overhead for the second index. The fewer indexes a table has, the better the insert, delete and update performance.

2022-08-08 09:06 UTC, morpheus-87 approved these changes

2022-08-08 09:06 UTC, merged