Adaptions for model 12
dbmdz/cudami pull request #1956
Opened 2022-08-18 11:29 UTC by clorenz

Add `RestControllerAdvice` for fixing POST/PUT/PATCH requests with missing `objectType to` heuristically set that field

2022-08-18 12:47 UTC, morpheus-87 requested changes

2022-08-18 12:47 UTC, morpheus-87 commented on dc-cudami-server/dc-cudami-server-webapp/src/test/java/de/digitalcollections/cudami/server/controller/advice/EnsureObjectTypeAdviceTest.java
> +  @DisplayName("handes requests for version 6 under different context")
```suggestion
  @DisplayName("handles requests for version 6 under different context")
```

2022-08-18 12:47 UTC, morpheus-87 commented on dc-cudami-server/dc-cudami-server-webapp/src/main/java/de/digitalcollections/cudami/server/controller/advice/EnsureObjectTypeAdvice.java
> +  @Autowired HttpServletRequest httpServletRequest;
Kann man das nicht im Kostruktor reingeben?

2022-08-19 08:23 UTC, clorenz commented on dc-cudami-server/dc-cudami-server-webapp/src/main/java/de/digitalcollections/cudami/server/controller/advice/EnsureObjectTypeAdvice.java
> +  @Autowired HttpServletRequest httpServletRequest;
ist umgebaut

2022-08-19 08:24 UTC, morpheus-87 approved these changes

2022-08-19 08:36 UTC, merged