Draft: Publication -> Publisher in Manifestation
dbmdz/cudami pull request #2105
Opened 2022-10-27 13:48 UTC by clorenz

2022-11-02 16:49 UTC, daforster requested changes

2022-11-02 16:49 UTC, daforster commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/JdbiRepositoryImpl.java
> +          // Collections: siehe SearchTermTemplates " DB @> query"
```suggestion
```

2022-11-02 16:49 UTC, daforster commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/JdbiRepositoryImpl.java
> +              && !((Collection<?>) fc.getValue()).isEmpty()) {
sollten wir hier schon nehmen können
```suggestion
              && !valueCollection.isEmpty()) {
```

2022-11-02 16:49 UTC, daforster commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/JdbiRepositoryImpl.java
> +                  criterionKey, ((Collection<?>) fc.getValue()).stream().toArray(UUID[]::new));
```suggestion
                  criterionKey, valueCollection.stream().toArray(UUID[]::new));
```

2022-11-02 16:49 UTC, daforster commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/JdbiRepositoryImpl.java
> +                  criterionKey, ((Collection<?>) fc.getValue()).stream().toArray(String[]::new));
```suggestion
                  criterionKey, valueCollection.stream().toArray(String[]::new));
```

2022-11-02 16:49 UTC, daforster commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/JdbiRepositoryImpl.java
> +                  criterionKey, ((Collection<?>) fc.getValue()).stream().toArray(Integer[]::new));
```suggestion
                  criterionKey, valueCollection.stream().toArray(Integer[]::new));
```

2022-11-02 16:49 UTC, daforster commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/JdbiRepositoryImpl.java
> +                  criterionKey, ((Collection<?>) fc.getValue()).stream().toArray(Long[]::new));
```suggestion
                  criterionKey, valueCollection.stream().toArray(Long[]::new));
```

2022-11-02 16:49 UTC, daforster commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/JdbiRepositoryImpl.java
> +              && !((Collection<?>) fc.getValue()).isEmpty()) {
```suggestion
              && !valueCollection.isEmpty()) {
```

2022-11-02 16:49 UTC, daforster commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/JdbiRepositoryImpl.java
> +            }
siehe oben.

Vllt. sollte man das als Funktion auslagern?

2022-11-02 16:49 UTC, daforster commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/PublisherRepositoryImpl.java
> +                + " cross join unnest(publ.location_uuids) l(id) " // Required to preserve order of
Sollten die `location_uuids` mal leer sein, würde der Eintrag nicht selektiert werden. Wäre hier nicht ein `LEFT JOIN` besser angebracht?

2022-11-03 10:25 UTC, clorenz commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/JdbiRepositoryImpl.java
> +          // Collections: siehe SearchTermTemplates " DB @> query"
ist entfernt

2022-11-03 10:25 UTC, clorenz commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/JdbiRepositoryImpl.java
> +              && !((Collection<?>) fc.getValue()).isEmpty()) {
fixed

2022-11-03 10:25 UTC, clorenz commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/JdbiRepositoryImpl.java
> +                  criterionKey, ((Collection<?>) fc.getValue()).stream().toArray(UUID[]::new));
fixed

2022-11-03 10:25 UTC, clorenz commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/JdbiRepositoryImpl.java
> +                  criterionKey, ((Collection<?>) fc.getValue()).stream().toArray(String[]::new));
fixed

2022-11-03 10:25 UTC, clorenz commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/JdbiRepositoryImpl.java
> +                  criterionKey, ((Collection<?>) fc.getValue()).stream().toArray(Integer[]::new));
fixed

2022-11-03 10:26 UTC, clorenz commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/JdbiRepositoryImpl.java
> +                  criterionKey, ((Collection<?>) fc.getValue()).stream().toArray(Long[]::new));
fixed

2022-11-03 10:26 UTC, clorenz commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/JdbiRepositoryImpl.java
> +              && !((Collection<?>) fc.getValue()).isEmpty()) {
fixed

2022-11-03 10:26 UTC, clorenz commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/JdbiRepositoryImpl.java
> +            }
Ja :) Ist ausgelagert.

2022-11-03 10:26 UTC, clorenz commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/PublisherRepositoryImpl.java
> +                + " cross join unnest(publ.location_uuids) l(id) " // Required to preserve order of
Ist gefixed

2022-11-03 10:47 UTC, daforster approved these changes

2022-11-03 10:51 UTC, daforster approved these changes

2022-11-03 10:58 UTC, merged