Show items for a manifestation
dbmdz/cudami pull request #2253
Opened 2023-02-15 15:10 UTC by clorenz

2023-02-15 15:22 UTC, daforster requested changes

2023-02-15 15:22 UTC, daforster commented on dc-cudami-server/dc-cudami-server-backend-api/src/main/java/de/digitalcollections/cudami/server/backend/api/repository/identifiable/entity/work/ManifestationRepository.java
> +  List<Locale> getLanguagesOfItems(UUID uuid);
Die beiden haben doch mit der Manifestation gar nichts zu tun (jedenfalls wird im Impl `itemRepository.retrieveList` aufgerufen). Daher gehört das m.E. ins ItemRepo.

2023-02-15 15:22 UTC, daforster commented on dc-cudami-server/dc-cudami-server-business/src/main/java/de/digitalcollections/cudami/server/business/api/service/identifiable/entity/work/ManifestationService.java
> +  List<Locale> getLanguagesOfItems(UUID uuid);
dito

2023-02-16 08:04 UTC, datazuul requested changes

2023-02-16 08:04 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-api/src/main/java/de/digitalcollections/cudami/server/backend/api/repository/identifiable/entity/work/ManifestationRepository.java
> +  List<Locale> getLanguagesOfItems(UUID uuid);
ja ins ItemRepo und umbenennen nach "findItemsByManifestation"

2023-02-16 08:36 UTC, clorenz commented on dc-cudami-server/dc-cudami-server-backend-api/src/main/java/de/digitalcollections/cudami/server/backend/api/repository/identifiable/entity/work/ManifestationRepository.java
> +  List<Locale> getLanguagesOfItems(UUID uuid);
Ist gemacht, vielen Dank, dass das aufgefallen ist

2023-02-16 08:37 UTC, clorenz commented on dc-cudami-server/dc-cudami-server-business/src/main/java/de/digitalcollections/cudami/server/business/api/service/identifiable/entity/work/ManifestationService.java
> +  List<Locale> getLanguagesOfItems(UUID uuid);
dito

2023-02-16 11:03 UTC, daforster approved these changes

2023-02-16 11:55 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-api/src/main/java/de/digitalcollections/cudami/server/backend/api/repository/identifiable/entity/work/ItemRepository.java
>    List<Item> getItemsForWork(UUID workUuid);
sollte wohl findItemsByWork heißen?

2023-02-16 11:55 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-api/src/main/java/de/digitalcollections/cudami/server/backend/api/repository/identifiable/entity/work/ItemRepository.java
> +  List<Locale> getLanguagesOfItemsForManifestation(UUID manifestationUuid);
bin mir nicht sicher bei anwendung "for" oder "by"...

2023-02-16 11:55 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/test/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/entity/work/ItemRepositoryImplTest.java
> +  @DisplayName("can retrieve items for a manifestation")
warum "can"?

2023-02-16 12:00 UTC, datazuul approved these changes

2023-02-16 12:00 UTC, merged