Sql migration fixes
dbmdz/cudami pull request #2554
Opened 2023-08-03 14:52 UTC by datazuul

- Fix saveUrlAlias (one question mark placeholder in sql more than given params)

2023-08-04 13:21 UTC, daforster submitted a review, later dismissed

2023-08-04 13:55 UTC, daforster commented
Vor dem Ausrollen auf DEV muss die Datenbank korrigiert werden:
```sql
delete from flyway_schema_history where version in ('14.04.00', '14.10.00');
```

2023-08-07 06:56 UTC, morpheus-87 commented on dc-cudami-admin/src/main/resources/templates/topics/view.html
> +            const baseUrl = [[@{'/identifiables'}]] + '/' + row.uuid;
Sollte das nicht besser `/entities` sein?

2023-08-07 08:51 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-webapp/src/main/java/de/digitalcollections/cudami/server/controller/converter/StringToFilterCriteriaGenericConverter.java
> +      operationValue.append(filterSource.substring(separatorPosition + 1));
passt schon, da "else" mit einem leeren StringBuilder aufgerufen wird

2023-08-08 05:27 UTC, datazuul commented on dc-cudami-admin/src/main/resources/templates/topics/view.html
> +            const baseUrl = [[@{'/identifiables'}]] + '/' + row.uuid;
done

2023-08-08 05:29 UTC, morpheus-87 requested changes

2023-08-08 05:29 UTC, morpheus-87 commented on dc-cudami-admin/src/main/java/de/digitalcollections/cudami/admin/controller/identifiable/AbstractIdentifiablesController.java
> +            "Unhandled object type " + identifiable.getIdentifiableObjectType());
Kann man hier nicht die Variable aus Zeile 113 nutzen?

2023-08-08 06:10 UTC, datazuul commented on dc-cudami-admin/src/main/java/de/digitalcollections/cudami/admin/controller/identifiable/AbstractIdentifiablesController.java
> +            "Unhandled object type " + identifiable.getIdentifiableObjectType());
ja, done

2023-08-08 07:41 UTC, morpheus-87 approved these changes

2023-08-08 07:43 UTC, merged