WIP: Entity relations part2
dbmdz/cudami pull request #588
Opened 2020-09-16 14:35 UTC by clorenz

Mass-deletion of entity relations by the tuple `(subject,predicate)`

2020-09-21 11:22 UTC, stefan-it commented
@dependabot rebase

2020-09-21 11:22 UTC, stefan-it commented
Rebase wäre gut zwecks GitHub Actions :)

2020-10-22 07:18 UTC, datazuul requested changes

2020-10-22 07:18 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-webapp/src/main/java/de/digitalcollections/cudami/server/controller/identifiable/entity/EntityRelationsController.java
> +      @ApiPathParam(description = "UUID of the subject") @PathVariable("subjectuuid")
required=true setzen, dann braucht es Zeile 77 nicht mehr, oder?

2020-12-16 12:22 UTC, closed without merging