WIP: Fix paging and refactor repository codes
dbmdz/cudami pull request #788
Opened 2021-01-08 15:37 UTC by datazuul

2021-01-26 10:25 UTC, morpheus-87 requested changes

2021-01-26 10:25 UTC, morpheus-87 commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/entity/relation/EntityRelationRepositoryImpl.java
> +    return allowedOrderByFields;
Kann man sich hier die Variablenzuweisung sparen?

2021-01-26 10:25 UTC, morpheus-87 commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/entity/relation/PredicateRepositoryImpl.java
> +    return allowedOrderByFields;
Kann man sich hier die Variablenzuweisung sparen?

2021-01-26 10:25 UTC, morpheus-87 commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/resource/TextFileResourceRepositoryImpl.java
> +    return allowedOrderByFields;
Kann man sich hier die Variablenzuweisung sparen?

2021-01-26 10:25 UTC, morpheus-87 commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/resource/ApplicationFileResourceRepositoryImpl.java
> +    return allowedOrderByFields;
Kann man sich hier die Variablenzuweisung sparen?

2021-01-26 10:25 UTC, morpheus-87 commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/resource/ApplicationFileResourceRepositoryImpl.java
> +  private final FileResourceMetadataRepositoryImpl fileResourceMetadataRepositoryImpl;
Vielleicht besser
```suggestion
  private final FileResourceMetadataRepositoryImpl metadataRepository;
```
?

2021-01-26 10:25 UTC, morpheus-87 commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/resource/AudioFileResourceRepositoryImpl.java
> +  private final FileResourceMetadataRepositoryImpl fileResourceMetadataRepositoryImpl;
Vielleicht besser
```suggestion
  private final FileResourceMetadataRepositoryImpl metadataRepository;
```
?

2021-01-26 10:25 UTC, morpheus-87 commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/resource/ApplicationFileResourceRepositoryImpl.java
> +        fileResourceMetadataRepositoryImpl.getAllowedOrderByFields();
Geht hier kein `super.`?

2021-01-26 10:25 UTC, morpheus-87 commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/resource/ImageFileResourceRepositoryImpl.java
> +  private final FileResourceMetadataRepositoryImpl fileResourceMetadataRepositoryImpl;
Vielleicht besser
```suggestion
  private final FileResourceMetadataRepositoryImpl metadataRepository;
```
?

2021-01-26 10:25 UTC, morpheus-87 commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/resource/LinkedDataFileResourceRepositoryImpl.java
> +  private final FileResourceMetadataRepositoryImpl fileResourceMetadataRepositoryImpl;
Vielleicht besser
```suggestion
  private final FileResourceMetadataRepositoryImpl metadataRepository;
```
?

2021-01-26 10:25 UTC, morpheus-87 commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/resource/TextFileResourceRepositoryImpl.java
> +  private final FileResourceMetadataRepositoryImpl fileResourceMetadataRepositoryImpl;
Vielleicht besser
```suggestion
  private final FileResourceMetadataRepositoryImpl metadataRepository;
```
?

2021-01-26 10:25 UTC, morpheus-87 commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/resource/VideoFileResourceRepositoryImpl.java
> +  private final FileResourceMetadataRepositoryImpl fileResourceMetadataRepositoryImpl;
Vielleicht besser
```suggestion
  private final FileResourceMetadataRepositoryImpl metadataRepository;
```
?

2021-01-26 12:07 UTC, datazuul commented on dc-cudami-client/src/main/java/de/digitalcollections/cudami/client/entity/agent/CudamiPersonsClient.java
> +        "/latest/persons/placeOfBirth/" + uuidGeoLocation.toString(), pageRequest);
ok

2021-01-26 12:07 UTC, datazuul commented on dc-cudami-client/src/main/java/de/digitalcollections/cudami/client/entity/agent/CudamiPersonsClient.java
> +        "/latest/persons/placeOfDeath/" + uuidGeoLocation.toString(), pageRequest);
ok

2021-01-26 12:08 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-api/src/main/java/de/digitalcollections/cudami/server/backend/api/repository/identifiable/NodeRepository.java
> +  boolean addChildren(UUID parentUuid, List<N> collections);
ok

2021-01-26 12:10 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/IdentifiableRepositoryImpl.java
> +    return new ArrayList<>(Arrays.asList("created", "label", "lastModified", "type"));
nein, das ist genau so richtig, denn Arrays.asList ist ummutable. ich will aber die liste später erweitern. das hatte exceptions gegeben

2021-01-26 12:12 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/resource/ApplicationFileResourceRepositoryImpl.java
> +        fileResourceMetadataRepositoryImpl.getAllowedOrderByFields();
dann müsste ich vererbung einführen (alle file repos erben dann von fileresourcemetadatarepo). ziemlicher aufwand. ich überlegs mir mal....

2021-01-26 12:12 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/IdentifierRepositoryImpl.java
> +    return allowedOrderByFields;
ok

2021-01-26 12:14 UTC, morpheus-87 commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/IdentifiableRepositoryImpl.java
> +    return new ArrayList<>(Arrays.asList("created", "label", "lastModified", "type"));
Gut, das ergibt natürlich Sinn :+1:

2021-01-26 12:14 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-webapp/src/main/java/de/digitalcollections/cudami/server/controller/PredicatesController.java
>  public class PredicatesController {
schön gesehen, ja.

2021-01-26 12:14 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-business/src/main/java/de/digitalcollections/cudami/server/business/impl/service/identifiable/IdentifiableServiceImpl.java
> +      labelOrder1.setSubProperty("de");
schön gesehen, ja.

2021-01-26 12:15 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-webapp/src/main/java/de/digitalcollections/cudami/server/controller/identifiable/entity/EntityRelationsController.java
>  package de.digitalcollections.cudami.server.controller.identifiable.entity;
schön gesehen, ja.

2021-01-26 12:17 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-business/src/main/java/de/digitalcollections/cudami/server/business/impl/service/identifiable/IdentifiableServiceImpl.java
> +      labelOrder1.setSubProperty("de");
habe auch im localerepository den default-wert "en" eingetragen, falls die config in application.yml fehlt

2021-01-26 12:18 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/entity/relation/EntityRelationRepositoryImpl.java
> +    return allowedOrderByFields;
ok

2021-01-26 12:19 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/IdentifierTypeRepositoryImpl.java
> +    return allowedOrderByFields;
ok

2021-01-26 12:19 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/entity/relation/PredicateRepositoryImpl.java
> +    return allowedOrderByFields;
ok

2021-01-26 12:22 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/resource/TextFileResourceRepositoryImpl.java
> +    return allowedOrderByFields;
ok

2021-01-26 12:22 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/resource/ApplicationFileResourceRepositoryImpl.java
> +    return allowedOrderByFields;
ok

2021-01-26 12:27 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/resource/TextFileResourceRepositoryImpl.java
> +  private final FileResourceMetadataRepositoryImpl fileResourceMetadataRepositoryImpl;
ok

2021-01-26 12:28 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/resource/ImageFileResourceRepositoryImpl.java
> +  private final FileResourceMetadataRepositoryImpl fileResourceMetadataRepositoryImpl;
ok

2021-01-26 12:44 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/resource/VideoFileResourceRepositoryImpl.java
> +  private final FileResourceMetadataRepositoryImpl fileResourceMetadataRepositoryImpl;
ok

2021-01-26 16:12 UTC, datazuul commented on dc-cudami-server/dc-cudami-server-backend-jdbi/src/main/java/de/digitalcollections/cudami/server/backend/impl/jdbi/identifiable/resource/ApplicationFileResourceRepositoryImpl.java
> +        fileResourceMetadataRepositoryImpl.getAllowedOrderByFields();
done

2021-01-27 09:25 UTC, morpheus-87 requested changes

2021-01-27 09:25 UTC, morpheus-87 commented on dc-cudami-client/src/main/java/de/digitalcollections/cudami/client/entity/agent/CudamiPersonsClient.java
> +        "/latest/persons/placeOfBirth/" + uuidGeoLocation.toString(), pageRequest);
Hier meinte ich eher die URL.

2021-01-27 09:25 UTC, morpheus-87 commented on dc-cudami-client/src/main/java/de/digitalcollections/cudami/client/entity/agent/CudamiPersonsClient.java
> +        "/latest/persons/placeOfDeath/" + uuidGeoLocation.toString(), pageRequest);
Hier meinte ich eher die URL.

2021-01-27 16:11 UTC, morpheus-87 commented on dc-cudami-client/src/main/java/de/digitalcollections/cudami/client/entity/agent/CudamiPersonsClient.java
> +        "/latest/persons/placeOfBirth/" + uuidGeoLocation.toString(), pageRequest);
:+1:

2021-01-27 16:11 UTC, morpheus-87 commented on dc-cudami-client/src/main/java/de/digitalcollections/cudami/client/entity/agent/CudamiPersonsClient.java
> +        "/latest/persons/placeOfDeath/" + uuidGeoLocation.toString(), pageRequest);
:+1:

2021-01-27 16:12 UTC, morpheus-87 approved these changes

2021-01-28 06:48 UTC, merged